const productos = [
    {id:19, tipo:"Remera", nombre:"Remera slash", precio: 1400, foto: "./media/slash.jpg" },
    {id:20, tipo:"Remera", nombre:"Remera nirvana", precio: 1400, foto: "./media/nirvana.jpg" },
    {id:21, tipo:"Remera", nombre:"Remera molotov", precio: 1000, foto: "./media/molotov.jpg" },
    {id:22, tipo:"Remera", nombre:"Remera metallica", precio: 1000, foto: "./media/metallica.jpg" },
    {id:23, tipo:"Remera", nombre:"Remera ceratti", precio: 1400, foto: "./media/ceratti.jpg" },
    {id:24, tipo:"Remera", nombre:"Remera gorillaz", precio: 1500, foto: "./media/gorillaz.jpg" },
    {id:25, tipo: "Buzo", nombre: "Buzo Scream", precio: 4500, foto: "./media/buzo scream.jpg"},
    {id:26, tipo: "Buzo", nombre: "Buzo Negro Oversized", precio: 3800, foto: "./media/buzo negro oversized.jpg"},
    {id:27, tipo: "Buzo", nombre: "Buzo Batik Oversized", precio: 3800, foto: "./media/buzo batik.jpg"},
    {id:10, tipo: "Buzo", nombre: "Hoddie Heads", precio: 3800, foto: "./media/hoddie heads.jpg"},
    {id:11, tipo: "Pantalon", nombre: "Jogging NC", precio: 2900, foto: "./media/pant logo.jpg"},
    {id:12, tipo: "Short", nombre: "Short Shining in the dark", precio: 1200, foto: "./media/short shining.jpg"},
    {id:13, tipo: "Short", nombre: "Short Notte", precio: 1000, foto: "./media/short notte.jpg"},
    {id:14, tipo: "Biker", nombre: "Biker black", precio: 1300, foto: "./media/biker black.jpg"},
    {id:15, tipo: "Accesorio", nombre: "Lentes Atria", precio: 2300, foto: "./media/lentes atria.jpg"},
    {id:16, tipo: "Accesorio", nombre: "Lentes Venatori", precio: 2400, foto: "./media/lentes venatori.jpg"},
    {id:17, tipo: "Accesorio", nombre: "Gorra rolling stone", precio: 800, foto: "./media/gorra-rolling stone.jpg"},
    {id:18, tipo: "Accesorio", nombre: "Gorra guns and rose", precio: 800, foto: "./media/guns and rose -gorra.jpg"},

];