const productos = [
    {id:1, tipo:"Remera", nombre:"Remera slash", precio: 2800, foto: "./media/slash.jpg" },
    {id:2, tipo:"Remera", nombre:"Remera nirvana", precio: 2400, foto: "./media/nirvana.jpg" },
    {id:3, tipo:"Remera", nombre:"Remera molotov", precio: 2500, foto: "./media/molotov.jpg" },
    {id:4, tipo:"Remera", nombre:"Remera metallica", precio: 3000, foto: "./media/metallica.jpg" },
    {id:5, tipo:"Remera", nombre:"Remera ceratti", precio: 2000, foto: "./media/ceratti.jpg" },
    {id:6, tipo:"Remera", nombre:"Remera gorillaz", precio: 2000, foto: "./media/gorillaz.jpg" },
    {id:7, tipo: "Buzo", nombre: "Buzo callejero", precio: 5500, foto: "./media/callejero buzo.jpg"},
    {id:8, tipo: "Buzo", nombre: "Buzo AC/DC", precio: 5800, foto: "./media/ac dc buzo.jpg"},
    {id:9, tipo: "Buzo", nombre: "Buzo Indio solari", precio: 5800, foto: "./media/indio buzo.jpg"},
    {id:10, tipo: "Buzo", nombre: "Buzo la renga", precio: 4800, foto: "./media/la renga buzo.jpg"},
    {id:11, tipo: "Pantalon", nombre: "Jogging NC", precio: 5900, foto: "./media/pantalon.jpg"},
    {id:12, tipo: "Short", nombre: "Short Shining in the dark", precio: 2200, foto: "./media/short shining.jpg"},
    {id:13, tipo: "Short", nombre: "Short Notte", precio: 2000, foto: "./media/short notte.jpg"},
    {id:14, tipo: "Biker", nombre: "Biker black", precio: 2300, foto: "./media/biker black.jpg"},
    {id:15, tipo: "Accesorio", nombre: "Lentes Roling Stone", precio: 6300, foto: "./media/lentes1.jpg"},
    {id:16, tipo: "Accesorio", nombre: "Lentes Ray-ban ", precio: 8400, foto: "./media/lentes2.jpg"},
    {id:17, tipo: "Accesorio", nombre: "Gorra rolling stone", precio: 1800, foto: "./media/gorra-rolling stone.jpg"},
    {id:18, tipo: "Accesorio", nombre: "Gorra guns and rose", precio: 1800, foto: "./media/guns and rose -gorra.jpg"},

];